@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.matyrobbrt.simpleminers.packsdatagen.simple;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;